liwcModelSelection:
  # Decision Tree
  DecisionTree: # actual class name
    criterion:
      - 'mse'
    splitter:
      - 'best'
    max_depth:
      - 5
    min_samples_split:
      - 2
    min_samples_leaf:
      - 50
    random_state:
      - 0
  # Ridge
  RidgeRegression:
    alpha:
      - 10.0
    random_state:
      - 0
  # GaussianProcessRegressor
  GaussianProcessRegressor:
    n_restarts_optimizer:
      - 0
    random_state:
      - 0
  # RandomForest
  RandomForest:
    criterion:
      - 'mse'
    n_estimators:
      - 100
    max_depth:
      - 10
    min_samples_split:
      - 5
    min_samples_leaf:
      - 10
    max_leaf_nodes:
      -  # None # recommended for Regression
    max_features:
      -  # None # recommended for Regression
    random_state:
      - 0
  # BayesianRidge
  BayesianRidge:
    n_iter:
      - 10
  SupportVectorMachine:
    kernel:
      - 'rbf'
    C: 
      - 10
    epsilon:
      - 0.1
    max_iter: 
      - 100

gloveModelSelection:
  # Decision Tree
  DecisionTree: # actual class name
    criterion:
      - 'mse'
    splitter:
      - 'best'
    max_depth:
      - 4
    min_samples_split:
      - 2
    min_samples_leaf:
      - 50
    random_state:
      - 0
#  # Ridge
#  RidgeRegression:
#    alpha:
#      - 20
#    random_state:
#      - 0
#  # GaussianProcessRegressor
#  GaussianProcessRegressor:
#    n_restarts_optimizer:
#      - 3
#    random_state:
#      - 0
  # RandomForest
  RandomForest:
    criterion:
      - 'mse'
    n_estimators:
      - 50
    max_depth:
      - 5
    min_samples_split:
      - 2
    min_samples_leaf:
      - 20
    max_leaf_nodes:
      -  # None
    max_features:
      - 450
    random_state:
      - 0
#  # BayesianRidge
#  BayesianRidge:
#    n_iter: 
#      - 25
  SupportVectorMachine:
    kernel:
      - 'linear'
    C: 
      - 0.01
    epsilon:
      - 0.1
    max_iter:
      - 300
